[package]
name = "crbasic-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "crbasic-lsp"
path = "src/main.rs"

[lib]
name = "crbasic_lsp"
path = "src/lib.rs"

[dependencies]
crbasic-parser = { path = "../crbasic-parser" }
tower-lsp-server = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
