//! Integration tests for parsing real-world CRBasic sample files
//!
//! These tests verify that the parser can handle actual CRBasic programs
//! generated by Campbell Scientific's LoggerNet software.

use crbasic_parser::ast::Statement;
use crbasic_parser::lexer::Scanner;
use crbasic_parser::{Parser, TokenKind};
use std::fs;
use std::path::PathBuf;

/// Returns the path to the sample-codes directory
fn sample_codes_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("../../docs/sample-codes")
}

/// Helper to read a sample file
fn read_sample_file(filename: &str) -> String {
    let path = sample_codes_dir().join(filename);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", filename, e))
}

/// Helper to tokenize source code
fn tokenize(source: &str) -> Vec<crbasic_parser::Token<'_>> {
    let mut scanner = Scanner::new(source);
    scanner.scan_tokens()
}

/// Helper to parse source code
fn parse(source: &str) -> Result<crbasic_parser::ast::Program, crbasic_parser::ParseError> {
    let tokens = tokenize(source);
    let mut parser = Parser::new(tokens);
    parser.parse()
}

mod tokenization {
    use super::*;

    #[test]
    fn tokenizes_cr1000_sample() {
        let source = read_sample_file("sample-cr1000.CR1");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
        assert!(
            matches!(
                tokens.last(),
                Some(crbasic_parser::Token {
                    kind: TokenKind::Eof,
                    ..
                })
            ),
            "Last token should be EOF"
        );
    }

    #[test]
    fn tokenizes_cr1000x_sample() {
        let source = read_sample_file("sample-cr1000x-series.CR1X");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr200_sample() {
        let source = read_sample_file("sample-cr200-series.CR2");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr300_sample() {
        let source = read_sample_file("sample-cr300-series.CR300");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr3000_sample() {
        let source = read_sample_file("sample-cr3000.CR3");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr5000_sample() {
        let source = read_sample_file("sample-cr5000.CR5");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr6_sample() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr800_sample() {
        let source = read_sample_file("sample-cr800-series.CR8");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr9000_sample() {
        let source = read_sample_file("sample-cr9000.CR9");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr9000x_sample() {
        let source = read_sample_file("sample-cr9000x.C9X");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }
}

mod parsing {
    use super::*;

    #[test]
    fn parses_cr1000_sample_without_errors() {
        let source = read_sample_file("sample-cr1000.CR1");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr1000x_sample_without_errors() {
        let source = read_sample_file("sample-cr1000x-series.CR1X");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr200_sample_without_errors() {
        let source = read_sample_file("sample-cr200-series.CR2");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr300_sample_without_errors() {
        let source = read_sample_file("sample-cr300-series.CR300");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr3000_sample_without_errors() {
        let source = read_sample_file("sample-cr3000.CR3");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr5000_sample_without_errors() {
        let source = read_sample_file("sample-cr5000.CR5");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr6_sample_without_errors() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr800_sample_without_errors() {
        let source = read_sample_file("sample-cr800-series.CR8");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr9000_sample_without_errors() {
        let source = read_sample_file("sample-cr9000.CR9");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    fn parses_cr9000x_sample_without_errors() {
        let source = read_sample_file("sample-cr9000x.C9X");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }
}

mod ast_structure {
    use super::*;

    /// Helper to check if a program contains BeginProg
    fn has_begin_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "BeginProg"
            )
        })
    }

    /// Helper to check if a program contains EndProg
    fn has_end_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndProg"
            )
        })
    }

    /// Helper to check if a program contains DataTable
    fn has_data_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "DataTable"
            )
        })
    }

    /// Helper to check if a program contains EndTable
    fn has_end_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndTable"
            )
        })
    }

    #[test]
    fn all_samples_have_begin_prog_and_end_prog() {
        let sample_files = [
            "sample-cr1000.CR1",
            "sample-cr1000x-series.CR1X",
            "sample-cr200-series.CR2",
            "sample-cr300-series.CR300",
            "sample-cr3000.CR3",
            "sample-cr5000.CR5",
            "sample-cr6-series.CR6",
            "sample-cr800-series.CR8",
            "sample-cr9000.CR9",
            "sample-cr9000x.C9X",
        ];

        for filename in sample_files {
            let source = read_sample_file(filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_begin_prog(&program),
                "{} should contain BeginProg",
                filename
            );
            assert!(
                has_end_prog(&program),
                "{} should contain EndProg",
                filename
            );
        }
    }

    #[test]
    fn all_samples_have_data_table_structure() {
        let sample_files = [
            "sample-cr1000.CR1",
            "sample-cr1000x-series.CR1X",
            "sample-cr200-series.CR2",
            "sample-cr300-series.CR300",
            "sample-cr3000.CR3",
            "sample-cr5000.CR5",
            "sample-cr6-series.CR6",
            "sample-cr800-series.CR8",
            "sample-cr9000.CR9",
            "sample-cr9000x.C9X",
        ];

        for filename in sample_files {
            let source = read_sample_file(filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_data_table(&program),
                "{} should contain DataTable",
                filename
            );
            assert!(
                has_end_table(&program),
                "{} should contain EndTable",
                filename
            );
        }
    }
}

mod semantic_analysis {
    use super::*;
    use crbasic_parser::semantic::{ErrorSeverity, SemanticError};
    use crbasic_parser::{DataloggerModel, SemanticAnalyzer};

    /// Helper to run semantic analysis on a sample file
    fn analyze_sample(filename: &str, model: DataloggerModel) -> Vec<SemanticError> {
        let source = read_sample_file(filename);
        let program = parse(&source).expect("Should parse successfully");
        let mut analyzer = SemanticAnalyzer::new(model);
        analyzer.analyze(&program)
    }

    #[test]
    fn cr6_sample_has_no_semantic_errors() {
        let errors = analyze_sample("sample-cr6-series.CR6", DataloggerModel::CR6);
        // Sample files may have warnings but should not have critical errors
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR6 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn cr1000_sample_analyzed_with_cr6_model() {
        // .cr1 is CR1000's own extension, which shares CR6's 39-char validation profile.
        let errors = analyze_sample("sample-cr1000.CR1", DataloggerModel::CR6);
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR1000 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn cr200_sample_analyzed_with_cr200x_model() {
        let errors = analyze_sample("sample-cr200-series.CR2", DataloggerModel::CR200X);
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR200 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn model_detection_works_for_sample_extensions() {
        // .cr1 is CR1000's own extension, not CR200(X)'s.
        assert_eq!(DataloggerModel::from_extension("cr1"), DataloggerModel::CR6);
        assert_eq!(
            DataloggerModel::from_extension("cr2"),
            DataloggerModel::CR200X
        );
        assert_eq!(DataloggerModel::from_extension("cr6"), DataloggerModel::CR6);
        // .crb is a generic extension shared across many models, not GRANITE-specific.
        assert_eq!(
            DataloggerModel::from_extension("crb"),
            DataloggerModel::Unknown
        );
        assert_eq!(DataloggerModel::from_extension("cr9"), DataloggerModel::CR6);
        assert_eq!(DataloggerModel::from_extension("c9x"), DataloggerModel::CR6);
    }
}

mod real_world_validation {
    use super::*;

    /// Verify that all sample files can be tokenized, parsed, and analyzed without errors
    #[test]
    fn all_sample_files_pass_complete_validation() {
        let sample_files = [
            ("sample-cr1000.CR1", crbasic_parser::DataloggerModel::CR6),
            (
                "sample-cr1000x-series.CR1X",
                crbasic_parser::DataloggerModel::CR6,
            ),
            (
                "sample-cr200-series.CR2",
                crbasic_parser::DataloggerModel::CR200X,
            ),
            (
                "sample-cr300-series.CR300",
                crbasic_parser::DataloggerModel::CR6,
            ),
            ("sample-cr3000.CR3", crbasic_parser::DataloggerModel::CR6),
            ("sample-cr5000.CR5", crbasic_parser::DataloggerModel::CR6),
            (
                "sample-cr6-series.CR6",
                crbasic_parser::DataloggerModel::CR6,
            ),
            (
                "sample-cr800-series.CR8",
                crbasic_parser::DataloggerModel::CR6,
            ),
            ("sample-cr9000.CR9", crbasic_parser::DataloggerModel::CR6),
            ("sample-cr9000x.C9X", crbasic_parser::DataloggerModel::CR6),
        ];

        for (filename, model) in sample_files {
            let source = read_sample_file(filename);

            let tokens = tokenize(&source);
            assert!(!tokens.is_empty(), "{}: Should produce tokens", filename);

            let program = parse(&source)
                .unwrap_or_else(|_| panic!("{}: Should parse successfully", filename));

            let mut analyzer = crbasic_parser::SemanticAnalyzer::new(model);
            let errors = analyzer.analyze(&program);
            let error_count = errors
                .iter()
                .filter(|e| e.severity == crbasic_parser::semantic::ErrorSeverity::Error)
                .count();

            assert_eq!(
                error_count, 0,
                "{}: Should have no semantic errors (found {} errors: {:?})",
                filename, error_count, errors
            );
        }
    }
}
