//! Integration tests for parsing real-world CRBasic sample files
//!
//! These tests verify that the parser can handle actual CRBasic programs
//! generated by Campbell Scientific's LoggerNet software.

use crbasic_parser::ast::Statement;
use crbasic_parser::lexer::Scanner;
use crbasic_parser::{DataloggerModel, Parser, TokenKind};
use std::fs;
use std::path::PathBuf;

/// Returns the path to the fixtures directory
fn fixtures_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("tests/fixtures")
}

/// Helper to read a fixture file
fn read_sample_file(filename: &str) -> String {
    let path = fixtures_dir().join(filename);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", filename, e))
}

/// Returns every fixture filename, sorted for deterministic iteration.
///
/// Iterating the directory (rather than a hardcoded list) is deliberate: a
/// hardcoded list previously let `sample-complex-realworld.CR6` sit outside
/// this suite's coverage, hiding the parenthesis-less `Call` bug fixed in #28.
fn fixture_filenames() -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(fixtures_dir())
        .unwrap_or_else(|e| panic!("Failed to read fixtures directory: {}", e))
        .map(|entry| entry.unwrap_or_else(|e| panic!("Failed to read directory entry: {}", e)))
        .filter(|entry| entry.path().is_file())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    names.sort();
    names
}

/// Derives the datalogger model a fixture file targets from its extension.
fn model_for_fixture(filename: &str) -> DataloggerModel {
    let extension = PathBuf::from(filename)
        .extension()
        .unwrap_or_else(|| panic!("{} has no file extension", filename))
        .to_string_lossy()
        .into_owned();
    DataloggerModel::from_extension(&extension)
}

/// Helper to tokenize source code
fn tokenize(source: &str) -> Vec<crbasic_parser::Token<'_>> {
    let mut scanner = Scanner::new(source);
    scanner.scan_tokens()
}

/// Helper to parse source code
fn parse(source: &str) -> Result<crbasic_parser::ast::Program, crbasic_parser::ParseError> {
    let tokens = tokenize(source);
    let mut parser = Parser::new(tokens);
    parser.parse()
}

mod tokenization {
    use super::*;

    #[test]
    fn every_fixture_tokenizes_to_a_non_empty_stream_ending_in_eof() {
        for filename in fixture_filenames() {
            let source = read_sample_file(&filename);
            let tokens = tokenize(&source);
            assert!(!tokens.is_empty(), "{}: should produce tokens", filename);
            assert!(
                matches!(
                    tokens.last(),
                    Some(crbasic_parser::Token {
                        kind: TokenKind::Eof,
                        ..
                    })
                ),
                "{}: last token should be EOF",
                filename
            );
        }
    }
}

mod parsing {
    use super::*;

    #[test]
    fn every_fixture_parses_without_errors() {
        for filename in fixture_filenames() {
            let source = read_sample_file(&filename);
            let result = parse(&source);
            assert!(
                result.is_ok(),
                "{}: should parse without errors: {:?}",
                filename,
                result
            );
        }
    }
}

mod ast_structure {
    use super::*;

    /// Helper to check if a program contains BeginProg
    fn has_begin_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "BeginProg"
            )
        })
    }

    /// Helper to check if a program contains EndProg
    fn has_end_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndProg"
            )
        })
    }

    /// Helper to check if a program contains DataTable
    fn has_data_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "DataTable"
            )
        })
    }

    /// Helper to check if a program contains EndTable
    fn has_end_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndTable"
            )
        })
    }

    #[test]
    fn every_fixture_has_begin_prog_and_end_prog() {
        for filename in fixture_filenames() {
            let source = read_sample_file(&filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_begin_prog(&program),
                "{} should contain BeginProg",
                filename
            );
            assert!(
                has_end_prog(&program),
                "{} should contain EndProg",
                filename
            );
        }
    }

    #[test]
    fn every_fixture_has_data_table_structure() {
        for filename in fixture_filenames() {
            let source = read_sample_file(&filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_data_table(&program),
                "{} should contain DataTable",
                filename
            );
            assert!(
                has_end_table(&program),
                "{} should contain EndTable",
                filename
            );
        }
    }
}

mod semantic_analysis {
    use super::*;
    use crbasic_parser::SemanticAnalyzer;
    use crbasic_parser::semantic::{ErrorSeverity, SemanticError};

    /// Helper to run semantic analysis on a sample file
    fn analyze_sample(filename: &str, model: DataloggerModel) -> Vec<SemanticError> {
        let source = read_sample_file(filename);
        let program = parse(&source).expect("Should parse successfully");
        let mut analyzer = SemanticAnalyzer::new(model);
        analyzer.analyze(&program)
    }

    #[test]
    fn cr6_sample_has_no_semantic_errors() {
        let errors = analyze_sample("sample-cr6-series.CR6", DataloggerModel::CR6);
        // Sample files may have warnings but should not have critical errors
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR6 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn cr1000_sample_analyzed_with_cr6_model() {
        // .cr1 is CR1000's own extension, which shares CR6's 39-char validation profile.
        let errors = analyze_sample("sample-cr1000.CR1", DataloggerModel::CR6);
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR1000 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn cr200_sample_analyzed_with_cr200x_model() {
        let errors = analyze_sample("sample-cr200-series.CR2", DataloggerModel::CR200X);
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR200 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn model_detection_works_for_sample_extensions() {
        // .cr1 is CR1000's own extension, not CR200(X)'s.
        assert_eq!(DataloggerModel::from_extension("cr1"), DataloggerModel::CR6);
        assert_eq!(
            DataloggerModel::from_extension("cr2"),
            DataloggerModel::CR200X
        );
        assert_eq!(DataloggerModel::from_extension("cr6"), DataloggerModel::CR6);
        // .crb is a generic extension shared across many models, not GRANITE-specific.
        assert_eq!(
            DataloggerModel::from_extension("crb"),
            DataloggerModel::Unknown
        );
        assert_eq!(DataloggerModel::from_extension("cr9"), DataloggerModel::CR6);
        assert_eq!(DataloggerModel::from_extension("c9x"), DataloggerModel::CR6);
    }
}

mod real_world_validation {
    use super::*;

    /// Verify that every fixture can be tokenized, parsed, and analyzed without errors,
    /// with the target model derived from the fixture's own file extension.
    #[test]
    fn every_fixture_passes_complete_validation() {
        for filename in fixture_filenames() {
            let model = model_for_fixture(&filename);
            let source = read_sample_file(&filename);

            let tokens = tokenize(&source);
            assert!(!tokens.is_empty(), "{}: Should produce tokens", filename);

            let program = parse(&source)
                .unwrap_or_else(|_| panic!("{}: Should parse successfully", filename));

            let mut analyzer = crbasic_parser::SemanticAnalyzer::new(model);
            let errors = analyzer.analyze(&program);
            let error_count = errors
                .iter()
                .filter(|e| e.severity == crbasic_parser::semantic::ErrorSeverity::Error)
                .count();

            assert_eq!(
                error_count, 0,
                "{}: Should have no semantic errors (found {} errors: {:?})",
                filename, error_count, errors
            );
        }
    }
}
