//! Integration tests for parsing real-world CRBasic sample files
//!
//! These tests verify that the parser can handle actual CRBasic programs
//! generated by Campbell Scientific's LoggerNet software.

use crbasic_parser::ast::Statement;
use crbasic_parser::lexer::Scanner;
use crbasic_parser::{Parser, TokenKind};
use std::fs;
use std::path::PathBuf;

/// Returns the path to the sample-codes directory
fn sample_codes_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("../../docs/sample-codes")
}

/// Helper to read a sample file
fn read_sample_file(filename: &str) -> String {
    let path = sample_codes_dir().join(filename);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", filename, e))
}

/// Helper to tokenize source code
fn tokenize(source: &str) -> Vec<crbasic_parser::Token> {
    let mut scanner = Scanner::new(source.to_string());
    scanner.scan_tokens()
}

/// Helper to parse source code
fn parse(source: &str) -> Result<crbasic_parser::ast::Program, crbasic_parser::ParseError> {
    let tokens = tokenize(source);
    let mut parser = Parser::new(tokens);
    parser.parse()
}

mod tokenization {
    use super::*;

    #[test]
    fn tokenizes_cr1000_sample() {
        let source = read_sample_file("sample-cr1000.CR1");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
        // Last token should be EOF
        assert!(
            matches!(
                tokens.last(),
                Some(crbasic_parser::Token {
                    kind: TokenKind::Eof,
                    ..
                })
            ),
            "Last token should be EOF"
        );
    }

    #[test]
    fn tokenizes_cr1000x_sample() {
        let source = read_sample_file("sample-cr1000x-series.CR1X");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr200_sample() {
        let source = read_sample_file("sample-cr200-series.CR2");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr300_sample() {
        let source = read_sample_file("sample-cr300-series.CR300");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr3000_sample() {
        let source = read_sample_file("sample-cr3000.CR3");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr5000_sample() {
        let source = read_sample_file("sample-cr5000.CR5");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr6_sample() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr800_sample() {
        let source = read_sample_file("sample-cr800-series.CR8");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr9000_sample() {
        let source = read_sample_file("sample-cr9000.CR9");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }

    #[test]
    fn tokenizes_cr9000x_sample() {
        let source = read_sample_file("sample-cr9000x.C9X");
        let tokens = tokenize(&source);
        assert!(!tokens.is_empty(), "Should produce tokens");
    }
}

mod parsing {
    use super::*;

    // NOTE: These tests are currently ignored because the parser doesn't yet support:
    // - Multiple variable declarations on single line (Public PTemp, Batt_volt)
    // - Boolean literals as function arguments (False, True)
    // - NextScan keyword
    // Run with `cargo test --ignored` to execute these tests

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr1000_sample_without_errors() {
        let source = read_sample_file("sample-cr1000.CR1");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr1000x_sample_without_errors() {
        let source = read_sample_file("sample-cr1000x-series.CR1X");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support Boolean literals"]
    fn parses_cr200_sample_without_errors() {
        let source = read_sample_file("sample-cr200-series.CR2");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr300_sample_without_errors() {
        let source = read_sample_file("sample-cr300-series.CR300");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr3000_sample_without_errors() {
        let source = read_sample_file("sample-cr3000.CR3");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr5000_sample_without_errors() {
        let source = read_sample_file("sample-cr5000.CR5");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr6_sample_without_errors() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr800_sample_without_errors() {
        let source = read_sample_file("sample-cr800-series.CR8");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr9000_sample_without_errors() {
        let source = read_sample_file("sample-cr9000.CR9");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }

    #[test]
    #[ignore = "Parser doesn't support comma-separated variable declarations"]
    fn parses_cr9000x_sample_without_errors() {
        let source = read_sample_file("sample-cr9000x.C9X");
        let result = parse(&source);
        assert!(result.is_ok(), "Should parse without errors: {:?}", result);
    }
}

mod ast_structure {
    use super::*;

    // NOTE: These tests are currently ignored because they depend on parsing,
    // which doesn't yet support comma-separated variable declarations or Boolean literals.
    // Run with `cargo test --ignored` to execute these tests

    /// Helper to check if a program contains BeginProg
    fn has_begin_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "BeginProg"
            )
        })
    }

    /// Helper to check if a program contains EndProg
    fn has_end_prog(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndProg"
            )
        })
    }

    /// Helper to check if a program contains DataTable
    fn has_data_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "DataTable"
            )
        })
    }

    /// Helper to check if a program contains EndTable
    fn has_end_table(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::ProgramStructure { keyword, .. } if keyword == "EndTable"
            )
        })
    }

    /// Helper to check if a program contains Public variable declaration
    fn has_public_declaration(program: &crbasic_parser::ast::Program) -> bool {
        program.statements.iter().any(|s| {
            matches!(
                s,
                Statement::VarDeclaration { keyword, .. } if keyword == "Public"
            )
        })
    }

    /// Helper to count function calls in a program
    fn count_function_calls(program: &crbasic_parser::ast::Program) -> usize {
        program
            .statements
            .iter()
            .filter(|s| matches!(s, Statement::FunctionCall { .. }))
            .count()
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr6_sample_contains_begin_prog_and_end_prog() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let program = parse(&source).expect("Should parse successfully");

        assert!(has_begin_prog(&program), "Should contain BeginProg");
        assert!(has_end_prog(&program), "Should contain EndProg");
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr6_sample_contains_data_table_structure() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let program = parse(&source).expect("Should parse successfully");

        assert!(has_data_table(&program), "Should contain DataTable");
        assert!(has_end_table(&program), "Should contain EndTable");
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr6_sample_contains_public_declaration() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let program = parse(&source).expect("Should parse successfully");

        assert!(
            has_public_declaration(&program),
            "Should contain Public declaration"
        );
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr6_sample_contains_function_calls() {
        let source = read_sample_file("sample-cr6-series.CR6");
        let program = parse(&source).expect("Should parse successfully");

        let call_count = count_function_calls(&program);
        assert!(call_count > 0, "Should contain at least one function call");
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr1000_sample_has_complete_program_structure() {
        let source = read_sample_file("sample-cr1000.CR1");
        let program = parse(&source).expect("Should parse successfully");

        assert!(has_begin_prog(&program), "Should contain BeginProg");
        assert!(has_end_prog(&program), "Should contain EndProg");
        assert!(has_data_table(&program), "Should contain DataTable");
        assert!(has_end_table(&program), "Should contain EndTable");
        assert!(
            has_public_declaration(&program),
            "Should contain Public declaration"
        );
    }

    #[test]
    #[ignore = "Depends on parser supporting Boolean literals"]
    fn cr200_sample_has_complete_program_structure() {
        let source = read_sample_file("sample-cr200-series.CR2");
        let program = parse(&source).expect("Should parse successfully");

        assert!(has_begin_prog(&program), "Should contain BeginProg");
        assert!(has_end_prog(&program), "Should contain EndProg");
        assert!(has_data_table(&program), "Should contain DataTable");
        assert!(has_end_table(&program), "Should contain EndTable");
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn all_samples_have_begin_prog_and_end_prog() {
        let sample_files = [
            "sample-cr1000.CR1",
            "sample-cr1000x-series.CR1X",
            "sample-cr200-series.CR2",
            "sample-cr300-series.CR300",
            "sample-cr3000.CR3",
            "sample-cr5000.CR5",
            "sample-cr6-series.CR6",
            "sample-cr800-series.CR8",
            "sample-cr9000.CR9",
            "sample-cr9000x.C9X",
        ];

        for filename in sample_files {
            let source = read_sample_file(filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_begin_prog(&program),
                "{} should contain BeginProg",
                filename
            );
            assert!(
                has_end_prog(&program),
                "{} should contain EndProg",
                filename
            );
        }
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn all_samples_have_data_table_structure() {
        let sample_files = [
            "sample-cr1000.CR1",
            "sample-cr1000x-series.CR1X",
            "sample-cr200-series.CR2",
            "sample-cr300-series.CR300",
            "sample-cr3000.CR3",
            "sample-cr5000.CR5",
            "sample-cr6-series.CR6",
            "sample-cr800-series.CR8",
            "sample-cr9000.CR9",
            "sample-cr9000x.C9X",
        ];

        for filename in sample_files {
            let source = read_sample_file(filename);
            let program = parse(&source).unwrap_or_else(|e| {
                panic!("Failed to parse {}: {:?}", filename, e);
            });

            assert!(
                has_data_table(&program),
                "{} should contain DataTable",
                filename
            );
            assert!(
                has_end_table(&program),
                "{} should contain EndTable",
                filename
            );
        }
    }
}

mod semantic_analysis {
    use super::*;
    use crbasic_parser::semantic::{ErrorSeverity, SemanticError};
    use crbasic_parser::{DataloggerModel, SemanticAnalyzer};

    // NOTE: Tests that depend on parsing are ignored until parser is enhanced

    /// Helper to run semantic analysis on a sample file
    fn analyze_sample(filename: &str, model: DataloggerModel) -> Vec<SemanticError> {
        let source = read_sample_file(filename);
        let program = parse(&source).expect("Should parse successfully");
        let mut analyzer = SemanticAnalyzer::new(model);
        analyzer.analyze(&program)
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr6_sample_has_no_semantic_errors() {
        let errors = analyze_sample("sample-cr6-series.CR6", DataloggerModel::CR6);
        // Sample files may have warnings but should not have critical errors
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR6 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    #[ignore = "Depends on parser supporting comma-separated declarations"]
    fn cr1000_sample_analyzed_with_cr200x_model() {
        let errors = analyze_sample("sample-cr1000.CR1", DataloggerModel::CR200X);
        // CR1000 sample should be compatible with CR200X model
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR1000 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    #[ignore = "Depends on parser supporting Boolean literals"]
    fn cr200_sample_analyzed_with_cr200x_model() {
        let errors = analyze_sample("sample-cr200-series.CR2", DataloggerModel::CR200X);
        let error_count = errors
            .iter()
            .filter(|e| e.severity == ErrorSeverity::Error)
            .count();
        assert_eq!(
            error_count, 0,
            "CR200 sample should have no semantic errors: {:?}",
            errors
        );
    }

    #[test]
    fn model_detection_works_for_sample_extensions() {
        assert_eq!(
            DataloggerModel::from_extension("cr1"),
            DataloggerModel::CR200X
        );
        assert_eq!(
            DataloggerModel::from_extension("cr2"),
            DataloggerModel::CR200X
        );
        assert_eq!(DataloggerModel::from_extension("cr6"), DataloggerModel::CR6);
        assert_eq!(
            DataloggerModel::from_extension("crb"),
            DataloggerModel::GRANITE
        );
        assert_eq!(DataloggerModel::from_extension("cr9"), DataloggerModel::CR6);
        assert_eq!(DataloggerModel::from_extension("c9x"), DataloggerModel::CR6);
    }
}
